### ISSUE TITLE
Which version of mmcv and mmdet are being used in the repo?

### ISSUE THREAD

**Issue by kanji95** [franciszzj/HiLo#6]
I am having trouble figuring out the version of these two libraries, as they are not included in the spec-file. With the latest version there are some import which are depricated (https://github.com/open-mmlab/mmcv/blob/c7c02a7c5ba25d37c7f7928013ffb3016e254eb9/docs/en/get_started/api_reference.md). Could you please share the version of mmcv and mmdet used in the project ?

**Comment by franciszzj** [comment]
mmcv==1.7.0
mmdet==2.25.2

**Comment by kanji95** [comment]
Thank you for your reply! I am getting the following error with these versions,
> Traceback (most recent call last):
  File "tools/test.py", line 19, in <module>
    from grade import save_results
  File "/home/mila/k/kanishk.jain/HiLo/tools/grade.py", line 11, in <module>
    from mmdet.datasets.coco_panoptic import INSTANCE_OFFSET
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/datasets/__init__.py", line 2, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/datasets/builder.py", line 15, in <module>
    from .samplers import (ClassAwareSampler, DistributedGroupSampler,
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/datasets/samplers/__init__.py", line 2, in <module>
    from .class_aware_sampler import ClassAwareSampler
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/datasets/samplers/class_aware_sampler.py", line 8, in <module>
    from mmdet.core.utils import sync_random_seed
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/core/__init__.py", line 3, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 8, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 12, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 3, in <module>
    from mmcv.ops import nms_match
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 3, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/mila/k/kanishk.jain/.conda/envs/hilo/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext

Did you ever encounter this error? Also, if possible could you please share the requirements or environment file?

**Comment by franciszzj** [comment]
It seems that your pytorch, cuda, and mmcv versions do not match.
More detailed solutions can be found at: https://github.com/open-mmlab/mmdetection/issues/3271#issuecomment-1192319876

**Comment by kanji95** [comment]
thanks a lot!
