### ISSUE TITLE
Error when training and testing HiLo(R50)

### ISSUE THREAD

**Issue by jinghang-chen** [franciszzj/HiLo#7]
Hello,
When I try to train and test HiLo(R50), the following error occurs, which does not occur in HiLo(baseline).
train:
**Traceback (most recent call last):
  File "tools/train.py", line 232, in <module>
    main()
  File "tools/train.py", line 169, in main
    dataset = build_dataset(cfg.data.train)
  File "/root/HiLo/openpsg/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, MMDET_DATASETS, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'**
test:
**Traceback (most recent call last):
  File "tools/test.py", line 775, in <module>
    main()
  File "tools/test.py", line 191, in main
    dataset = build_dataset(cfg.data.test)
  File "/root/HiLo/openpsg/datasets/builder.py", line 42, in build_dataset
    dataset = build_from_cfg(cfg, MMDET_DATASETS, default_args)
  File "/root/miniconda3/lib/python3.8/site-packages/mmcv/utils/registry.py", line 72, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'**
Do you know the reason?

**Comment by franciszzj** [comment]
Please check whether the mmcv and mmdet versions you are using are the recommended versions mentioned in the README.

**Comment by jinghang-chen** [comment]
> Please check whether the mmcv and mmdet versions you are using are the recommended versions mentioned in the README.

Thank you for your reply.
I think the reason may be that I am using mmcv-full==1.7.0.
When I use mmcv==1.7.0, I get a "ModuleNotFoundError: No module named 'mmcv._ext'" error.
I've seen how to solve this error in other issues.
Many thanks!

**Comment by franciszzj** [comment]
Glad to know you solved the problem.
